### ISSUE TITLE
Says that "SAM" is not a command

### ISSUE THREAD

**Issue by 03172008** [StudioChew/samauto#1]
Would you be able to put the SAM command files inside the samauto folder? I think that would make it easier and remove most errors.

> materwelon // -SpamCauldron-

**Comment by StudioChew** [comment]
the Software Automatic Mouth is not my own product, and i would not feel ok with putting it in with samauto. this is why you have to drag samauto.bat in your windows_sam folder.

**Comment by 03172008** [comment]
Ok thank you, that explains why.

**Comment by 03172008** [comment]
But can you say in the readme.md to drag the whole unzipped sam folder, then drag the sam.exe into the samauto folder that has all the stuff in it? I think that would help people to solve the issue... But it's your decision...

**Comment by StudioChew** [comment]
already in the readme.md to extract/drag contents of samauto.zip to sam folder

**Comment by 03172008** [comment]
oh ok thanks...
